perfDataBig = [];
perfDataBig2 = [];
perfDataBigSD = [];

load lum1.mat;

x = 0.4:0.01:0.8;
y = exp(-(1/(2*0.1^2)).*((x-0.6).^2));


runString = ['_JONLUMINANCE_0'];
eval(['fileStr = ''perfdata' runString ''';']);
eval(['load ./dataTemp/' fileStr ';']);
eval(['goodOrNot = size(' fileStr ',1);']);
if goodOrNot > 0
%            eval(['perfDataBig = [perfDataBig; [mean(' fileStr ') 10*exp(-(1/(2*(0.1)^2).*(luminance-0.8).^2))]];']);
    eval(['perfDataBig = ' fileStr ';']);
%             eval(['perfDataBigSD = [perfDataBigSD; [luminance std(' fileStr ')./sqrt(goodOrNot)]];']);
end
% eval(['perfDataBig2 = [perfDataBig2; [luminance 10*exp(-(1/(2*(0.1)^2).*(luminance-0.8).^2))]];']);
            


fignum = figure('Units', 'pixels', 'Position', [100 20 600 500]);
hold off;
% hPlot = plot(perfDataBig(1:end,1),perfDataBig(1:end,2));
% hErr = errorbar(perfDataBig(1:end,1),perfDataBig(1:end,2), perfDataBigSD(1:end,2));
hist(perfDataBig,0:0.01:10);
%axis([0 0.7 0 200]);

figure(fignum)

hXLabel = xlabel('Reaction time (s)'                     );
hYLabel = ylabel('Frequency'                      );

set(gca                      , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 30        );





set(gca, ...
  'FontSize'    , 36        , ... 
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , 0:0.1:4.0, ...
  'YTick'       , [30 60 90], ...
  'LineWidth'   , 2         );

% set(hErr, ...
%     'Color'     , [1.0 1.0 1.0]    ,   ...
%     'Marker'          , 'o'         , ...
%     'MarkerSize'      , 10           , ...
%     'MarkerEdgeColor' , [0 0 0]  , ...
%     'MarkerFaceColor' , [0 0 1]  , ...
%     'LineWidth' ,1         );

% axis([0.23 0.35 0.0 110]);
 
set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 ~/Dropbox/luminance_plot_hist.eps

% fignum = figure('Units', 'pixels', 'Position', [100 20 600 500]);
% hold off;
% % hPlot = plot(perfDataBig(1:end,1),perfDataBig(1:end,2));
% % hErr = errorbar(perfDataBig(1:end,1),perfDataBig(1:end,2), perfDataBigSD(1:end,2));
% hist(luminance,10);
% hold on;
% % hErr = plot(x,y.*75);
% 
% figure(fignum)
% 
% hXLabel = xlabel('Luminance value'                     );
% hYLabel = ylabel('Frequency'                      );
% 
% set(gca                      , ...
%     'FontName'   , 'Helvetica' );
% set([hXLabel, hYLabel], ...
%     'FontName'   , 'Helvetica');
% set([hXLabel, hYLabel]  , ...
%     'FontSize'   , 30        );
% 
% 
% 
% 
% 
% set(gca, ...
%   'FontSize'    , 36        , ... 
%   'Box'         , 'off'     , ...
%   'TickDir'     , 'out'     , ...
%   'TickLength'  , [.02 .02] , ...
%   'XMinorTick'  , 'off'      , ...
%   'YMinorTick'  , 'off'      , ...
%   'YGrid'       , 'off'      , ...
%   'XColor'      , [.3 .3 .3], ...
%   'YColor'      , [.3 .3 .3], ...
%   'XTick'       , [0 0.4  0.6  0.8 ], ...
%   'YTick'       , [30 60 90], ...
%   'LineWidth'   , 2         );
% % 
% % set(hErr, ...
% %     'Color'     , [0.4 0.4 0.4]    ,   ...
% %     'LineWidth' ,2         );
% 
% % axis([0.25 1.0 0.0 80]);
%  
% set(gcf, 'PaperPositionMode', 'auto');
% print -depsc2 ~/luminance_plot_src.eps

