%%%%% CURRENT DEFAULT WEIGHTS AND VALUES FOR FULL MODEL!
%%%%% REVISION HISTORY:
%%%%% 02/04/09 - ALEX COPE - created
%%%%% 02/04/09b - ALEX COPE - added striatal projection type control
%%%%% 03/04/09 - ALEX COPE - branched from full model version
%%%%% 23/04/09 - ALEX COPE - added support for ventral stream ver 3 gating
%%%%% 27/04/09 - ALEX COPE - added adjustment of LIP -> FEF
%%%%% 27/04/09 - ALEX COPE - added THAL_THRESHOLDS
%%%%% 09/06/09 - ALEX COPE - added DOPAMINE
%%%%% 30/11/09 - ALEX COPE - updated
%%%%% 04/01/10 - ALEX COPE - complete revision of values for updated model

targetMode = false;
field_vs = false;

%% ####### DOPAMINE ########
DOPAMINE = 0.2;

%% ###### OcM SYSTEM: ######

INPUT_NOISE = 0.01;
MEMB_NOISE = 0.01;
SIG_NOISE = 0; % multiplicative to signals only
BACKGROUND_NOISE = 0.0; % additive to everything
STIM_NOISE = 20;

%% RETINA
RETINA2_TO_RETINA1 = -1.2;

%% SUPERIOR COLLICULUS
SC_SUPERIOR_TO_SC_BUILDUP = 10.0;
SC_BUILDUP_RECIP = 1.0;
SC_BUILDUP_RECIP_INH = 0.0;

%% THALAMUS, FEF
THAL_2_FEF = 0.5;
FEF_2_THAL = 3.0;
        
%% OcM BASAL GANGLIA
STRIATAL_OFFSET = 0.05;

STR_D1_TO_SNR = -1.0*2;
STR_D2_TO_GPE = -1.0*2;

STN_TO_SNR = 2.4; % NOTE: SCALED BY LAYER SIZE! SNR weight MUST = GPe weight
STN_TO_GPE = 1.0; % NOTE: SCALED BY LAYER SIZE!

GPE_TO_STN = -1.4;
GPE_TO_SNR = -0.4;

STR_IN_SIGMA = 1.5;
STR_IN_TYPE = 'onetoone';
proj_type = ''; % '' for normal cartesian, 'LP' for log/polar

%% FEF TO BASAL GANGLIA
FEF_TO_STR_D1 = 1.5;
FEF_TO_STR_D2 = 1.5;
FEF_TO_STN = 6.0; % NOTE: SCALED BY LAYER SIZE!

%% THALAMUS TO BASAL GANGLIA
THAL_TO_STR_D1 = 1.0;
THAL_TO_STR_D2 = 1.0;
THAL_TO_STN = 6.0; % NOTE: SCALED BY LAYER SIZE!

%% PHASIC INPUT
RETINA1_TO_FEF = 0.0; % DISABLED FOR NOW!
RETINA1_TO_SC_SUPERIOR = 2.0;

%% THALAMIC INPUT
SC_SUPERIOR_TO_THAL = 0.3;
SC_BUILDUP_TO_THAL = 0.6;
SNR_TO_THAL = -2.5;
SNR_TO_THAL_ADD = -0.5;
THAL_THRESHOLD = 0.125;
THAL_RESET = 0.135;

%% SC BUILDUP INPUT
FEF_TO_SC_BUILDUP = 10;
SNR_TO_SC_BUILDUP = -5.0;
SNR_TO_SC_BUILDUP_ADD = -0.0;

%% SACCADIC GENERATOR INHIBITION
SG_TO_SC_BUILDUP = -200.0;
SG_TO_FEF = 0.0;
SG_TO_RETINA1 = -1.0;
SG_TO_VIS = -1.0;

%% FIXATION NO-GO
FIX_NOGO_BIAS = 0.6;
FIX_ZONE_D2_DRIVE = 0.7; %0.56 when world lum is 0.4 and STR_W = 0.8 - this simulates a PFC command to not latch up fixation
FIX_ZONE_WIDTH = 40;
FIX_TO_OPN = 0.05;

%% ###### VISUAL SYSTEM: ######

%% CROSS CONNECTIONS
LIP_TO_FEF = 0.25;
VS_IN = 0.4;

%% BASAL GANGLIA
VS_STR_D1_TO_SNR = -0.9;
VS_STR_D2_TO_GPE = -0.9;

VS_STN_TO_SNR = 1.0;
VS_STN_TO_GPE = 1.0;

VS_GPE_TO_STN = -1.0;
VS_GPE_TO_SNR = -0.3;

VS_SNR_TO_THAL = -0.0;
VS_TRN_TO_THAL_WITHIN = -0.45 * 2.0 * 0.3;
VS_TRN_TO_THAL_OUTSIDE = -0.45 * 2.0;
VS_THAL_TO_TRN = 1.0;

%% BASAL GANGLIA INPUT
IT_TO_STR_D1 = 1.0;
IT_TO_STR_D2 = 1.0;
IT_TO_STN = 13.0;

%% GAIN LOOPS
IT_TO_TRN = 1.0;
IT_TO_THAL = 0.0;
THAL_TO_IT = 2.0;
IT_RECIP = 0.0;

%% GATING WEIGHTS
FEEDFORWARD_WEIGHT_GATING = 1.0;
FEEDBACK_WEIGHT_GATING = 2.0;
RECIPROCAL_WEIGHT_GATING = 0.0;
ATTENTIONAL_WEIGHT_GATING = 0.0;
FEATURE_INHIBITION_GATING = -1.6;

%% ADD WEIGHTS
FEEDFORWARD_WEIGHT_ADD = 0.5;
FEEDBACK_WEIGHT_ADD = 0.3;
RECIPROCAL_WEIGHT_ADD = 0.0;
FEATURE_INHIBITION_ADD = -1.6;

%% SHUNT WEIGHTS
FEEDFORWARD_WEIGHT_SHUNT = 0.3;
FEEDBACK_WEIGHT_SHUNT = 2.5;
RECIPROCAL_WEIGHT_SHUNT = 0.15;
FEATURE_INHIBITION_SHUNT = -1.6;

%% DK WEIGHTS
% N/I !


%% GATING VER 3 WEIGHTS
FEEDFORWARD_WEIGHT_GATING3 = 1.0;
FEEDBACK_WEIGHT_GATING3 = 6.0;%3.3
RECIPROCAL_WEIGHT_GATING3 = 0.0;
ATTENTIONAL_WEIGHT_GATING3 = 0.0;
FEATURE_INHIBITION_GATING3 = -0.6;

%% ADD VER 3 WEIGHTS
FEEDFORWARD_WEIGHT_ADD3 = 0.7;
FEEDBACK_WEIGHT_ADD3 = 0.3;
RECIPROCAL_WEIGHT_ADD3 = 0.0;
FEATURE_INHIBITION_ADD3 = -0.7;

%% SHUNT VER 3 WEIGHTS
FEEDFORWARD_WEIGHT_SHUNT3 = 1.0;
FEEDBACK_WEIGHT_SHUNT3 = 0.9;
RECIPROCAL_WEIGHT_SHUNT3 = 0.15;
FEATURE_INHIBITION_SHUNT3 = -0.7;
