function niceGraph( hGraph, star, fin )
%Make a pretty graph
%   Detailed explanation goes here


len = (fin-star)/100;
str = {};

for i = 1:len
    str{i} = '';
end

set(gca, ...
  'FontSize'    , 20        , ... 
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .03] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , [0:100:10000], ...
  'XTickLabel',{str{:},'100ms'}, ...
  'YTick'       , [0 1.0], ...
  'LineWidth'   , 2         );

 axis([0 fin-star 0 1.0]);

set(hGraph, ...
    'Color'     , [0.0 0.0 0.0]    ,   ...   
    'LineWidth' , 2         );
    
    

end

